import { useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { EmptyState, ErrorState, LoadingState, PageHeader, RatingDisplay, SortButton, StatCard } from "@/components/AppShell";

const roleLabels = { admin: "Administrator", user: "Normal user", owner: "Store owner" } as const;
const formatDate = (value: Date | string) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));

function Pager({ page, total, pageSize, setPage }: { page: number; total: number; pageSize: number; setPage: (page: number) => void }) { const pages = Math.max(1, Math.ceil(total / pageSize)); return <div className="pagination"><span>Showing {total ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, total)} of {total}</span><div className="pagination-actions"><button onClick={() => setPage(page - 1)} disabled={page <= 1}>←</button><button onClick={() => setPage(page + 1)} disabled={page >= pages}>→</button></div></div>; }

export default function AdminDashboard() {
  const dashboard = trpc.admin.dashboard.useQuery();
  if (dashboard.isLoading) return <LoadingState />;
  if (dashboard.error) return <ErrorState message={dashboard.error.message} />;
  const counts = dashboard.data ?? { users: 0, stores: 0, ratings: 0 };
  return <div><PageHeader eyebrow="System administrator" title="Good morning, admin." description="A quick read on the StoreMate network. Keep the directory clean and the signal useful." action={<Link href="/admin/stores" className="primary-button">Add a store <span>+</span></Link>} /><div className="stats-grid"><StatCard label="Total users" value={counts.users} detail="All registered accounts" tone="ink" /><StatCard label="Registered stores" value={counts.stores} detail="Across the StoreMate directory" tone="amber" /><StatCard label="Submitted ratings" value={counts.ratings} detail="Every rating in the network" tone="blue" /></div><div className="section-head"><div><h2>Admin shortcuts</h2><p>The areas you will use most often.</p></div></div><div className="quick-grid"><Link href="/admin/stores" className="card quick-card"><span className="quick-symbol">⌂</span><strong>Manage stores</strong><p>Add stores, review addresses and monitor overall ratings.</p></Link><Link href="/admin/users" className="card quick-card"><span className="quick-symbol">◉</span><strong>Review people</strong><p>Search users, check roles and open full profile details.</p></Link><Link href="/admin/users" className="card quick-card"><span className="quick-symbol">↕</span><strong>Keep data tidy</strong><p>Use filters and sorting to find the right record quickly.</p></Link></div></div>;
}

export function AdminUsersPage() {
  const [search, setSearch] = useState(""); const [address, setAddress] = useState(""); const [role, setRole] = useState<"user" | "admin" | "owner" | undefined>(); const [page, setPage] = useState(1); const [sortBy, setSortBy] = useState<"name" | "email" | "address" | "role">("name"); const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc"); const [showForm, setShowForm] = useState(false);
  const users = trpc.admin.users.useQuery({ search, address, role, page, pageSize: 8, sortBy, sortDirection, includeOwners: true });
  const toggleSort = (next: typeof sortBy) => { if (sortBy === next) setSortDirection(current => current === "asc" ? "desc" : "asc"); else { setSortBy(next); setSortDirection("asc"); } setPage(1); };
  return <div><PageHeader eyebrow="Directory / people" title="People" description="Normal users, administrators and store owners, organized for quick review." action={<button className="primary-button" onClick={() => setShowForm(value => !value)}>{showForm ? "Close form" : "Add a user"} <span>{showForm ? "×" : "+"}</span></button>} />{showForm && <CreateUserCard /> }<div className="card table-card"><div className="table-toolbar"><div className="toolbar-search"><span className="search-icon">⌕</span><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Search by name or email" /></div><input className="filter-input" value={address} onChange={event => { setAddress(event.target.value); setPage(1); }} placeholder="Filter address" /><select className="filter-input" value={role ?? ""} onChange={event => { setRole((event.target.value || undefined) as typeof role); setPage(1); }}><option value="">All roles</option><option value="user">Normal user</option><option value="admin">Administrator</option><option value="owner">Store owner</option></select></div>{users.isLoading ? <LoadingState /> : users.error ? <ErrorState message={users.error.message} /> : !users.data?.rows.length ? <EmptyState title="No people found" message="Try widening your search or clearing a filter." /> : <><div className="data-table-wrap"><table className="data-table"><thead><tr><th><SortButton label="Name" active={sortBy === "name"} direction={sortDirection} onClick={() => toggleSort("name")} /></th><th><SortButton label="Email" active={sortBy === "email"} direction={sortDirection} onClick={() => toggleSort("email")} /></th><th><SortButton label="Address" active={sortBy === "address"} direction={sortDirection} onClick={() => toggleSort("address")} /></th><th><SortButton label="Role" active={sortBy === "role"} direction={sortDirection} onClick={() => toggleSort("role")} /></th><th>Profile</th></tr></thead><tbody>{users.data.rows.map(user => <tr key={user.id}><td><span className="cell-primary">{user.name}</span><span className="cell-secondary">Joined {formatDate(user.createdAt)}</span></td><td>{user.email}</td><td>{user.address}</td><td><span className={`role-badge ${user.role}`}>{roleLabels[user.role]}</span></td><td><Link href={`/admin/users/${user.id}`} className="secondary-button">View</Link></td></tr>)}</tbody></table></div><Pager page={page} total={users.data.total} pageSize={8} setPage={setPage} /></>}</div></div>;
}

function CreateUserCard() {
  const utils = trpc.useUtils(); const mutation = trpc.admin.createUser.useMutation({ onSuccess: async () => { await utils.admin.users.invalidate(); setForm({ name: "", email: "", password: "", address: "", role: "user" }); setMessage("User created successfully."); } });
  const [form, setForm] = useState({ name: "", email: "", password: "", address: "", role: "user" as "user" | "admin" | "owner" }); const [message, setMessage] = useState(""); const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm(current => ({ ...current, [key]: event.target.value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); setMessage(""); mutation.mutate(form); };
  return <div className="card form-card" style={{ marginBottom: 18 }}><div className="section-head"><div><h2>Add a user</h2><p>Name, email, address and role are stored with the account.</p></div></div><form className="form-grid" onSubmit={submit}><label className="field"><span>Name</span><input value={form.name} onChange={update("name")} placeholder="20–60 characters" required /></label><label className="field"><span>Email</span><input type="email" value={form.email} onChange={update("email")} required /></label><label className="field"><span>Password</span><input type="password" value={form.password} onChange={update("password")} placeholder="8–16 chars, uppercase + special" required /></label><label className="field"><span>Role</span><select value={form.role} onChange={update("role")}><option value="user">Normal user</option><option value="admin">Administrator</option><option value="owner">Store owner</option></select></label><label className="field form-span"><span>Address</span><textarea value={form.address} onChange={update("address")} maxLength={400} required /></label>{(mutation.error || message) && <div className={(mutation.error ? "form-alert" : "success-state") + " form-span"}>{mutation.error?.message ?? message}</div>}<button className="primary-button form-span" disabled={mutation.isPending}>{mutation.isPending ? "Creating…" : "Create user"}</button></form></div>;
}

export function AdminStoresPage() {
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [sortBy, setSortBy] = useState<"name" | "email" | "address" | "rating">("name"); const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc"); const [showForm, setShowForm] = useState(false);
  const stores = trpc.admin.stores.useQuery({ search, page, pageSize: 8, sortBy, sortDirection }); const owners = trpc.admin.users.useQuery({ role: "owner", includeOwners: true, page: 1, pageSize: 50, sortBy: "name", sortDirection: "asc" });
  const toggleSort = (next: typeof sortBy) => { if (sortBy === next) setSortDirection(current => current === "asc" ? "desc" : "asc"); else { setSortBy(next); setSortDirection("asc"); } setPage(1); };
  return <div><PageHeader eyebrow="Directory / stores" title="Stores" description="The registered directory, with an overall rating read at a glance." action={<button className="primary-button" onClick={() => setShowForm(value => !value)}>{showForm ? "Close form" : "Add a store"} <span>{showForm ? "×" : "+"}</span></button>} />{showForm && <CreateStoreCard owners={owners.data?.rows ?? []} /> }<div className="card table-card"><div className="table-toolbar"><div className="toolbar-search"><span className="search-icon">⌕</span><input value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} placeholder="Search by store, email or address" /></div></div>{stores.isLoading ? <LoadingState /> : stores.error ? <ErrorState message={stores.error.message} /> : !stores.data?.rows.length ? <EmptyState title="No stores found" message="Add the first store or change your search." /> : <><div className="data-table-wrap"><table className="data-table"><thead><tr><th><SortButton label="Name" active={sortBy === "name"} direction={sortDirection} onClick={() => toggleSort("name")} /></th><th><SortButton label="Email" active={sortBy === "email"} direction={sortDirection} onClick={() => toggleSort("email")} /></th><th><SortButton label="Address" active={sortBy === "address"} direction={sortDirection} onClick={() => toggleSort("address")} /></th><th><SortButton label="Rating" active={sortBy === "rating"} direction={sortDirection} onClick={() => toggleSort("rating")} /></th></tr></thead><tbody>{stores.data.rows.map(store => <tr key={store.id}><td className="cell-primary">{store.name}</td><td>{store.email}</td><td>{store.address}</td><td><RatingDisplay value={store.rating} /></td></tr>)}</tbody></table></div><Pager page={page} total={stores.data.total} pageSize={8} setPage={setPage} /></>}</div></div>;
}

function CreateStoreCard({ owners }: { owners: Array<{ id: number; name: string; email: string }> }) {
  const utils = trpc.useUtils(); const mutation = trpc.admin.createStore.useMutation({ onSuccess: async () => { await utils.admin.stores.invalidate(); setForm({ name: "", email: "", address: "", ownerId: "" }); setMessage("Store created successfully."); } });
  const [form, setForm] = useState({ name: "", email: "", address: "", ownerId: "" }); const [message, setMessage] = useState(""); const update = (key: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm(current => ({ ...current, [key]: event.target.value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); setMessage(""); mutation.mutate({ ...form, ownerId: form.ownerId ? Number(form.ownerId) : null }); };
  return <div className="card form-card" style={{ marginBottom: 18 }}><div className="section-head"><div><h2>Add a store</h2><p>Give the directory a complete record and optionally assign an owner.</p></div></div><form className="form-grid" onSubmit={submit}><label className="field"><span>Store name</span><input value={form.name} onChange={update("name")} placeholder="20–60 characters" required /></label><label className="field"><span>Store email</span><input type="email" value={form.email} onChange={update("email")} required /></label><label className="field"><span>Store owner</span><select value={form.ownerId} onChange={update("ownerId")}><option value="">Unassigned</option>{owners.map(owner => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select></label><label className="field form-span"><span>Address</span><textarea value={form.address} onChange={update("address")} maxLength={400} required /></label>{(mutation.error || message) && <div className={(mutation.error ? "form-alert" : "success-state") + " form-span"}>{mutation.error?.message ?? message}</div>}<button className="primary-button form-span" disabled={mutation.isPending}>{mutation.isPending ? "Creating…" : "Create store"}</button></form></div>;
}

export function UserDetailPage({ id }: { id: number }) { const detail = trpc.admin.userDetail.useQuery({ id }); if (detail.isLoading) return <LoadingState />; if (detail.error) return <ErrorState message={detail.error.message} />; if (!detail.data) return <EmptyState title="User not found" message="This profile may have been removed." />; const { user, ownedStore } = detail.data; return <div className="narrow-page"><PageHeader eyebrow="People / profile" title="User detail" description="The complete account record available to the administrator." action={<Link href="/admin/users" className="secondary-button">← Back to people</Link>} /><div className="card detail-card"><div className="detail-grid"><div className="detail-item"><span>Name</span><strong>{user.name}</strong></div><div className="detail-item"><span>Role</span><strong><span className={`role-badge ${user.role}`}>{roleLabels[user.role]}</span></strong></div><div className="detail-item"><span>Email</span><strong>{user.email}</strong></div><div className="detail-item"><span>Address</span><strong>{user.address}</strong></div><div className="detail-item"><span>Joined</span><strong>{formatDate(user.createdAt)}</strong></div><div className="detail-item"><span>Last signed in</span><strong>{formatDate(user.lastSignedIn)}</strong></div>{ownedStore && <div className="detail-item"><span>Store / average rating</span><strong>{ownedStore.name}<br /><RatingDisplay value={ownedStore.averageRating} /></strong></div>}</div></div></div>; }
