import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { EmptyState, ErrorState, LoadingState, PageHeader, RatingDisplay } from "@/components/AppShell";

function RatingEditor({ value, onSave, pending }: { value: number | null; onSave: (rating: number) => void; pending: boolean }) {
  const [selected, setSelected] = useState(value ?? 0); return <div><div className="rating-control" role="group" aria-label="Choose a rating from 1 to 5">{[1,2,3,4,5].map(score => <button type="button" key={score} className={score <= selected ? "selected" : ""} onClick={() => setSelected(score)} aria-label={`${score} out of 5`}>★</button>)}</div>{selected > 0 && selected !== value && <button className="rating-save" onClick={() => onSave(selected)} disabled={pending}>{pending ? "Saving…" : value ? "Update" : "Save rating"}</button>}</div>;
}

export default function StoresPage() {
  const [search, setSearch] = useState(""); const [appliedSearch, setAppliedSearch] = useState(""); const [page, setPage] = useState(1); const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc");
  const stores = trpc.stores.list.useQuery({ search: appliedSearch, page, pageSize: 8, sortDirection }); const utils = trpc.useUtils(); const rating = trpc.ratings.submit.useMutation({ onSuccess: async () => { await utils.stores.list.invalidate(); } });
  const submitSearch = (event: React.FormEvent) => { event.preventDefault(); setAppliedSearch(search); setPage(1); }; const pages = Math.max(1, Math.ceil((stores.data?.total ?? 0) / 8));
  return <div><PageHeader eyebrow="Normal user workspace" title="Find your next favorite." description="Browse registered stores, see the overall signal and add your own perspective." /><div className="card table-card"><div className="table-toolbar"><form className="toolbar-search" onSubmit={submitSearch}><span className="search-icon">⌕</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by store name or address" /></form><button className="secondary-button" onClick={() => setSortDirection(current => current === "asc" ? "desc" : "asc")}>Name {sortDirection === "asc" ? "↑" : "↓"}</button></div>{stores.isLoading ? <LoadingState label="Finding stores…" /> : stores.error ? <ErrorState message={stores.error.message} /> : !stores.data?.rows.length ? <EmptyState title="No stores found" message="Try a different name or address." /> : <><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Store</th><th>Address</th><th>Overall rating</th><th>Your rating</th><th>Rate this store</th></tr></thead><tbody>{stores.data.rows.map(store => <tr key={store.id}><td><span className="cell-primary">{store.name}</span><span className="cell-secondary">{store.email}</span></td><td>{store.address}</td><td><RatingDisplay value={store.rating} /></td><td>{store.userRating ? <RatingDisplay value={store.userRating} /> : <span className="cell-secondary">Not rated yet</span>}</td><td><RatingEditor value={store.userRating} onSave={value => rating.mutate({ storeId: store.id, rating: value })} pending={rating.isPending} /></td></tr>)}</tbody></table></div><div className="pagination"><span>{stores.data.total} stores in the directory</span><div className="pagination-actions"><button onClick={() => setPage(page - 1)} disabled={page <= 1}>←</button><span style={{ padding: "7px 5px" }}>{page} / {pages}</span><button onClick={() => setPage(page + 1)} disabled={page >= pages}>→</button></div></div></>}</div>{rating.error && <ErrorState message={rating.error.message} />}</div>;
}
